service: CustomAuth
custom:
  secrets: ${file(secrets.json)}
provider:
  name: aws
  runtime: nodejs10.x
  profile: default
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.jwtSecret}
functions:
  login:
    handler: functions/login.handler
    events:
      - http:
          path: valid
          method: post
          cors: true
  authorize:
    handler: functions/authorize.handler
  getUsers:
    handler: functions/getUsers.handler
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer: authorize

